<?php

namespace AppBundle\Repository;

/**
 * ParkingLotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParkingLotRepository extends \Doctrine\ORM\EntityRepository
{
}
